---
- name: Enable ExpandPersistenVolumes on Master
  yedit:
    src: '{{ expand_pv_master_config }}'
    key: kubernetesMasterConfig.{{ item }}.feature-gates
    value:
    - ExpandPersistentVolumes=true
    state: present
    backup: yes
  with_items:
     - apiServerArguments
     - controllerArguments

- name: Enable PersistentVolumeClaimResize on Master
  yedit:
    src: '{{ expand_pv_master_config }}'
    key: admissionConfig.pluginConfig.PersistentVolumeClaimResize.configuration
    value: |
      apiVersion: v1
      disable: false
      kind: DefaultAdmissionConfig
    state: present
    backup: yes

- name:  Restart master api
  service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - atomic-openshift-master-api
    - atomic-openshift-master-controllers